const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0I1VHpzRTFIZmJob2FIaXFBM1ZCUml0U3FyOS9NR2dhaEc2VEg4bU5tWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTWZ0VzVvYzNTRUI1RURzR1lMejMxQkltd2lnS2ZVMzV3KzJLNTdueHVYRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJTEN2cmdlS1JOTTVpVjVYZ29sTFo3enZZL0VsNVBsU2xSMkpkbHJhQms4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJYb3FHK2REaEJWWkZyVjlJMThnLzJHR1Awai9TMGlSQzRuSTd6UzVLcGtBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFERDZJbklJTEE4Slh3TDFtR201TE10OUd3NW1HT2pQUWhtcHdFM2RWVUk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjlpcUpaM1lZYWw0MUZ1ZmFCWkpWVnNDV1AvQllEei8wWWJsNDAwbGJqSDg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUJ3enlpc2t3Z1d3RlJobVROTmdxaVlaeUcwdE9ZQWdkdDBvSGh1L09tWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRHhsWFVNeTZLTC9IajVmSCtxMDhwcjZNNURPc0M5bEo5bjFKaCtFa0NpUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlhCUm1tL3NVRm5KVWtZOGhEN1hheStTM3lrbHBoR3RMNk5Bb3gxZCt6OVNJWlBSd1VlY1VpQVpuNFZERjUyaFlMM0VDVHZCemgwcCt0SEw5S3B6R0JBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTQsImFkdlNlY3JldEtleSI6IkFOT2ZkVkVxZlJhUmtFNE1mOFVqR2Z5L2wxaXB3VmhaZWhuWnRCYjBjNFE9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6InN5M1FMSUh3UlZhLVZUQVo3dHdHd2ciLCJwaG9uZUlkIjoiNGViMDM0NDItYmUwOS00ZDc3LWEwNjktMDAwYTdhZDg0M2MyIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkkzekFyOE8zOHdFU3FqdXZhdUk5d1RMM2grbz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpZ3I1cEFrWU44UERXb0FnZUFwWDNQamxtTWM9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiVldCSFRLNTIiLCJtZSI6eyJpZCI6IjI1NDc5OTIxMTM1Nzo3NkBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTktGcDhrSEVPZndpNzhHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQzN3L0RQUENyVGdqcDM2eVV1S1dBbmdLN0pRMWpRUHkvSDBOcHRHQXFrST0iLCJhY2NvdW50U2lnbmF0dXJlIjoicmw1TTBpd3BYK0EwWG9NMXRFRUhPM0JYSmxBMlpTejk5ODU0NEk2dWN1S1hRamF5ZTVKSXJNZTZUWTBRRHl1UFRWQWd4V1J0eWVWS0tJckFaTVpVRGc9PSIsImRldmljZVNpZ25hdHVyZSI6InlGenBndUlNa0R1eUZzeVp0UVVvR2haNTlXZm0xbm42dkxJUGFHekY0VG1Tdm5mK3ZHQTJDUHA3WlVJVDVRU3dad3JVaHpzdnV6eVNHZEJRdVBuU0J3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0Nzk5MjExMzU3Ojc2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlF0OFB3enp3cTA0STZkK3NsTGlsZ0o0Q3V5VU5ZMEQ4dng5RGFiUmdLcEMifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDI5Mjc5OTQsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRTAyIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
